### ISSUE TITLE
请问作者遇到过不稳定的问题吗

### ISSUE THREAD

**Issue by Zafirzzf** [yichengchen/RabbitVpnDemo#15]
一开始可以连接成功并且出墙，但是后面连接成功，国内国外的网站都无法访问了..排除了账号问题。

**Comment by Zafirzzf** [comment]
一开始可以连接成功并且出墙,但是后面连接成功,国内国外的网站都无法访问了..排除了账号问题.

**Comment by yichengchen** [comment]
这只是个demo……
