### ISSUE TITLE
连上去就断开啊怎么办，怎么办？

### ISSUE THREAD

**Issue by zhaoyunyi** [yichengchen/RabbitVpnDemo#20]
xcode 9.1 swift 4
carthage 下来的库没有任何问题，权限开了personVPN 和NE扩展，单独NE扩展也试过了
能正常运行，连接就是崩溃

**Comment by zhaoyunyi** [comment]
连上去有VPN 的标记，然后访问www.google.com 网站就断开了

**Comment by yichengchen** [comment]
请检查系统崩溃日志

**Comment by yuzhijiang** [comment]
有没有解决，我的也是偶尔连接就断开

**Comment by madonya** [comment]
> 连上去有VPN 的标记，然后访问www.google.com 网站就断开了

请问你解决了吗
