### ISSUE TITLE
切换网络导致所有网页不能访问

### ISSUE THREAD

**Issue by yuanjilee** [yichengchen/RabbitVpnDemo#24]
**提供的 demo 运行完全没有问题**

但是我另写了一个例子，当切换网络后，导致所有网页不能访问，必须删除程序重新运行才可以。 但是和demo 完全一模一样的代码。通过断点发现

```
override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
        if keyPath == "defaultPath" {
            if self.defaultPath?.status == .satisfied && self.defaultPath != lastPath{
                if(lastPath == nil){
                    lastPath = self.defaultPath
                }else{
                    NSLog("received network change notifcation")
                    let delayTime = DispatchTime.now() + Double(Int64(1 * Double(NSEC_PER_SEC))) / Double(NSEC_PER_SEC)
                    DispatchQueue.main.asyncAfter(deadline: delayTime) {
                        self.startTunnel(options: nil){_ in}
                    }
                }
            }else{
                lastPath = defaultPath
            }
        }
        
    }
```

~每次切换网络后，`self.defaultPath?.status == .satisfied` 判断为 `false`,  不会再次调用 ` self.startTunnel(options: nil){_ in}` 启动 tunnel ，也不会多次得到通知直到 `status` 为正确状态。~
确实不是切换网络的问题，本质是 tunnel 为启动成功造成的，但是还没有找到解决方案
那么，请问
是demo 中有我未发现的其他配置导致的吗？

**Comment by yuanjilee** [comment]
发现问题了，是因为切换网络后 `WLAN 与蜂窝移动网`关闭了。  但是我并没有设置获取网络的权限，为什么 demo 没有此问题，看了 plist 也没有多余的设置，请问是其他设置导致的吗？

**Comment by CoderJin** [comment]
https://github.com/yichengchen/RabbitVpnDemo/blob/master/PacketTunnel/PacketTunnelProvider.swift#L17


看看这里 这里tun 没有开启 你切换网络状态不会有影响的

**Comment by wangedoo** [comment]
@CoderJin  我也遇到相同的问题，这里tun 没有开启？？？具体解决方案是？

**Comment by yuanjilee** [comment]
@CoderJin  
你好，很感谢回复。如你所说，确实不是切换网络造成的，很有可能是 tun 的开启失败。但是如 demo 所示，有的情况下回开启成功，有时则不然，具体没有找到原因。  根据你的回复，以及接下来又做了很多尝试，参数 `enablePacketProcessing ` 即使设置为 true 也不能保证 tun 每次的正确开启。
最终，还是没有找到问题的根源，希望能不吝指教，谢谢~

**Comment by CoderJin** [comment]
https://github.com/zhuhaow/NEKit

**Comment by CoderJin** [comment]
[](https://github.com/zhuhaow/NEKit)

**Comment by CoderJin** [comment]
[https://github.com/zhuhaow/NEKit](url)

**Comment by CoderJin** [comment]
[看这个](https://github.com/zhuhaow/NEKit)

**Comment by wangedoo** [comment]
是不是最近两天不能用了   @yuanjilee 你那里还能连接成功吗？

**Comment by arvincong** [comment]
What is the end of this question？how can i do something for this
