### ISSUE TITLE
在10.2上面链接 ss 服务器能正常使用，其他版本的操作系统就一直链接不上，是什么原因呢

### ISSUE THREAD

**Issue by sqzxcv** [yichengchen/RabbitVpnDemo#25]
hi，你好，请教一个问题：
下载您的 demo，目前只在ios 10.2上 成功使用ss 打开了 google，其他版本都失败了。
在10.3上，vpn 能建立并打开，但是访问谷歌的时候，提示 adapter Socket disconnect。（ss 服务器正常的）。在9.3上，vpn 建立后就根本打不开，也看不到 log，没办法定位问题具体原因，还望大神指导一下~~

**Comment by sqzxcv** [comment]
1. 在9.3上没有跑起来的原因，是 extension 支持的最低操作系统不支持9.3，修改一下就好了。
2. 但是在10.3上，建立vpn 后，访问谷歌，提示“Socket closed by remote peer”

**Comment by LIXIAOJIE123** [comment]
导入NEKit之前是可以建立vpn通道，但是导入NEKit之后按照作者demo去配置PacketTunnelProvider之后，现在vpn通道无法建立。
