### ISSUE TITLE
使用您的代码核心做了一个 app

### ISSUE THREAD

**Issue by ChengLuffy** [yichengchen/RabbitVpnDemo#28]
[ChengLuffy/ShadowsocksFree](https://github.com/ChengLuffy/ShadowsocksFree)

目的是抓取 网上免费限时节点 以度过自建节点不稳定时期，JP 系列可以满足日常需求

应该上架不了，依然十分感谢 yicheng 大佬

**Comment by yichengchen** [comment]
赞👍
