### ISSUE TITLE
能够正常连接VPN，但是无法访问网络

### ISSUE THREAD

**Issue by kevin-lxh** [yichengchen/RabbitVpnDemo#31]
修改setRulerConfig方法下的 adress、port、method、password、ymal_conf 等信息，运行
启动后，点击Connect，VPN正常连接，但是无法访问任何网页，可能是什么问题？

iOS version: 11.2.1
Device: iPhone X

![img_2623](https://user-images.githubusercontent.com/5647241/39958953-e5eb6f4c-563c-11e8-9c7c-cc7033710351.PNG)

**Comment by ViterbiDevelopment** [comment]
是什么原因呢？我的也出现了这样的情况

**Comment by zhoubo6419** [comment]
你们找到原因了嘛？
