### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by lampchop** [yichengchen/RabbitVpnDemo#7]
你好， 

carthage update后， build 提示
 linker command failed with exit code 1 (use -v to see invocation)

![pachettunnel](https://cloud.githubusercontent.com/assets/12220151/26023069/211b7118-37e7-11e7-9dda-3959e6056d8a.png)

xcode 8.3.2 , mac 10.12.4

这可能是哪方面的原因呢

**Comment by SamCoder123** [comment]
我也是这个问题 希望作者能解答一下 主要是 老是提示确少CommonCrypto.framework

**Comment by q0988113683** [comment]
https://github.com/q0988113683/RabbitVpnDemo.git

**Comment by ZenonHuang** [comment]
先是一样报  linker command failed with exit code 1 。

使用了 @q0988113683 的，结果报的：
Failed to read file or folder at  xxxx/Carthage/Build/iOS/CommonCrypto.framework
Command /bin/sh failed with exit code 1

仍然不行，应该脚本执行出了问题。

**Comment by q0988113683** [comment]
請再試一次
下載後，請先執行Cartfile，把目錄的CommonCrypto.framework複製到RabbitVpnDemo-Shadowsocks/Carthage/Build

**Comment by ZenonHuang** [comment]
CommonCrypto.framework 在哪个位置？只看到有一个 CommonCrypto-master 项目文件，并没有 framework. 是需要自己去编译吗
