### ISSUE TITLE
Error Domain=NEConfigurationErrorDomain Code=11 "IPC failed" UserInfo={NSLocalizedDescription=IPC failed}

### ISSUE THREAD

**Issue by lampchop** [yichengchen/RabbitVpnDemo#8]
Hi，

模拟器的错误提示 Error Domain=NEConfigurationErrorDomain Code=11 "IPC failed" UserInfo={NSLocalizedDescription=IPC failed}

用真机调试没有log， 只是点击connect 然后提示connecting 然后就off了， 配置文件设置过ss的配置信息了。

xcode 8.3.2 , mac 10.12.4

**Comment by zhaoyunyi** [comment]
@lampchop  请问你是怎么解决 的呀

**Comment by zhaoyunyi** [comment]
@lampchop  ，我的情况跟你一样，我配置什么的都改好了呀。。为什么会这样？谢谢告知

**Comment by lampchop** [comment]
忘了，期间出了很多问题。有的是缺模块，有的是网络不挂代理git 不到等。查了好多资料，试了好久，然后就好了

**Comment by zhaoyunyi** [comment]
我不缺模块，shell代理git库 也解决了，现在就是跑起来没效果，connect 一下就直接off了，你有合适能跑的工程能分享给我么，或者发挥一下您强大的记忆力回忆一下😝

**Comment by lampchop** [comment]
我找了一下以前的笔记，只看到一个NE模块没启用的笔记，然而并不是这个问题😂

**Comment by lampchop** [comment]
我用的就是这个完整模块，一样的代码啊

**Comment by lampchop** [comment]
这个应该是必须真机调试的。你看看它的配置是不是大小写，或者拼写错误，我模糊的记得是这个问题，yaml 什么的

**Comment by zhaoyunyi** [comment]
我也是用的真机，NEKit 的模块代码，还有这个demo没动直接跑，改了下ID，还有扩展的权限，甚至自己重新搞了个工程也是同样的问题

**Comment by lampchop** [comment]
Easy, easy，多看看，应该可以🤣🤣🤣

**Comment by lampchop** [comment]
这个大佬的代码，就是全网基本唯一的可用代码了

**Comment by zhaoyunyi** [comment]
ymal_conf 我看代码 是直接从项目的配置文件里读取的

**Comment by zhaoyunyi** [comment]
是啊，我找了一下午，唯一看起来靠谱的，然后还跑不起来。。很伤心

**Comment by lampchop** [comment]
没事，我搞了几个星期🤣🤣🤣

**Comment by zhaoyunyi** [comment]
额。。。大佬，拯救我的周末啊

**Comment by zhaoyunyi** [comment]
override func startTunnel(options: [String : NSObject]?, completionHandler: @escaping (Error?) -> Void) 
就是那个扩展的 Target 的代码 就是不跑，没输出。。不知道咋回事

**Comment by lampchop** [comment]
扩展里的要用attach调试，你查一下，如何调试extension ，貌似这位大佬的博客里也说了。

**Comment by zhaoyunyi** [comment]
那我调试一下看看，希望有好消息

**Comment by zhaoyunyi** [comment]
还是不行，哭😢

**Comment by zhaoyunyi** [comment]
@lampchop  是不是这个模块 CommonCrypto.framework 没导进来，你的那个笔记上是这个吗

**Comment by lampchop** [comment]
@zhaoyunyi 我那个记的是NE权限没开。模块是那个

**Comment by lampchop** [comment]
conf["ss_address"] = "YOUR SS URL" as AnyObject?
你如果没有改这里的host地址， 跑不起来的， vpnmanager的

**Comment by zhaoyunyi** [comment]
我这里 PersonVPN 和NetworkeExtension 的扩展都开了，而且两个Target 都开了，ss_address 用的是我自己能连上的服务器的地址和密码

**Comment by lampchop** [comment]
@zhaoyunyi 只要开NE就行了

**Comment by lampchop** [comment]
你慢慢调试， 应该是小问题，看一下调试数据，easy，easy ，你可以的 (^_^)a

**Comment by zhaoyunyi** [comment]
我关了只剩NE Capabilities 也不行额。。不知道哪里崩溃。。attch  调试也看不到，真是见了鬼了。。。

**Comment by lampchop** [comment]
这个大佬的代码我改了比较多， 以前的版本也没有保留。只有靠你自己了，你可以的。(*^o^*)， 没错，yichengchen大佬即将附体，助你完工

**Comment by zhaoyunyi** [comment]
好惨啊，就是连上去断开连上去断开。。。好气。。也什么错误提示

**Comment by zhaoyunyi** [comment]
@lampchop  终于发现问题了。。我曹。。
        switch method{
        case "AES128CFB":algorithm = .AES128CFB
        case "AES192CFB":algorithm = .AES192CFB
        case "AES256CFB":algorithm = .AES256CFB
        case "CHACHA20":algorithm = .CHACHA20
        case "SALSA20":algorithm = .SALSA20
        case "RC4MD5":algorithm = .RC4MD5 
        default:
            fatalError("Undefined algorithm!")
        }
这里的配置跟我之前 ss 的 配置字符串不一样。。。所以直接崩掉了。。现在是连上去 VPN 上一个google 然后就直接断掉。。。又一个问题

**Comment by lampchop** [comment]
对，我刚是不是也提醒你这个了。🙈🙈🙈🙈配置问题

**Comment by lampchop** [comment]
那你可能需要更新一下？我最后用的最新Xcode 9，swift也是最新版，nekit也是🙈🙈🙈

**Comment by zhaoyunyi** [comment]
我也是用的最新的IDE 和最新的swift 版本，nekit 也是，配置问题我想着没错的啊。。。谁知道里面还有个字符串匹配。。奶奶的。。现在就是访问以下就会直接断掉。。有没有qq 或者微信加下，有空再向你请教，我感觉这里还有很多坑。。要死了。。我的qq 529503769

**Comment by lampchop** [comment]
没有啊，我手下好几千人，一秒钟几十万上下🙈🙈🙈，忙不过来。另外，你要心存感激，注意措辞，毕竟是大佬在带着我们

**Comment by zhaoyunyi** [comment]
那您留个邮件呗，碰到迈不过去坎，请教一下您，这个demo 是可以的啊，就是怕后面优化起来还有很多NE的坑

**Comment by lampchop** [comment]
吹牛可以，写代码，我不行🤣🤣🤣🤣

**Comment by yichengchen** [comment]
所有跑不起来的建议切分支到BasicTest（单纯建立vpn连接不引入nekit）验证是否能建立连接。
